[book]
authors = ["Jan Van Bouwel"]
language = "en"
multilingual = false
src = "src"
title = "Krikata"

[preprocessor.build]
command = "node mdbook-build.js"


[preprocessor.cmdrun]
after = ["build"]
